# Generated by Django 4.1.dev20211001111137 on 2021-10-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=120)),
                ('Department', models.CharField(max_length=120)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFile', models.CharField(max_length=100)),
            ],
        ),
    ]
